#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

docker run \
     -p 3008:3008/tcp \
     -v $DIR/../dist:/app/dist \
     openstax/labs.frontend.ci:latest \
     yarn run test:ci
