#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

CMD=$1

docker run \
    -p 4000:4000/tcp \
    -v $DIR/../dist:/app/dist \
    "${PACKAGE:=openstax/labs.frontend:latest}" \
    yarn run $CMD
