import { Box, React, styled, useState } from '@common';
import { Button, Icon, OffCanvas } from '@components';
import FAQIcon from '@images/icons/faq.svg'

const FAQButton = styled.img({
    cursor: 'pointer',
    height: 50,
    width: 50,
})

const StyledOffCanvas = styled(OffCanvas)({
    '.offcanvas-body': {
        height: 'auto',
    },
})

export const ResearcherFAQ: FC = () => {
    const [show, setShow] = useState(false)

    return (
        <div>
            <FAQButton src={FAQIcon} alt='faq-icon' onClick={() => setShow(true)} />
            <StyledOffCanvas show={show} title='Help' onHide={() => setShow(false)}>
                <AnalysisBasicsFAQ />
            </StyledOffCanvas>
        </div>
    )
}

export const AnalysisBasicsFAQ: FC = () => {
    const [currentSection, setCurrentSection] = useState('')

    return (
        <Box direction='column'>
            <FAQSection title='What are Enclaves and what is the purpose of this method?' setCurrentSection={setCurrentSection} currentSection={currentSection}>
                <p>On Kinetic, we understand that researchers need to know who the learners are to effectively address the impact of learner characteristics on learning outcomes.</p>

                <p>These characteristics can range from socio-demographic information (e.g., race, gender, SES, etc.) to psychosocial constructs that may impact learning (e.g., goal orientation, anxiety, etc.), and are key to surfacing issues of inequity in educational opportunities and outcomes.</p>

                <p>And data is crucial for large-scale education research (we’re referring to larger than gigabytes - at terabyte or petabyte level), but sharing it with researchers poses important challenges on a privacy level, and additional technical and logistical barriers.</p>

                <p>To address this problem, traditional approaches often resort to methods such as reducing data size or de-identifying their data, which leads to loss of critical student and contextual factors, and ultimately hinders researchers trying to understand how different learner characteristics impact different learning interventions and resulting outcomes.</p>

                <strong>Kinetic Approach</strong>
                <p>At Kinetic, we’re instead choosing to adopt modern confidential computing practices for large-scale educational research that are shifting the paradigm from traditional practices – that is, we bring researcher’s analytical software to the data instead of bringing the data to the researcher.</p>

                <p>This approach entails the use of secure enclaves for data analysis - a protected containerized environment that enables researchers to analyze all individual data points without direct access to the data, instead returning aggregated knowledge, ultimately reducing significant privacy risks.</p>
            </FAQSection>

            <FAQSection title='How are synthetic datasets generated on Kinetic?' setCurrentSection={setCurrentSection} currentSection={currentSection}>
                <p>Kinetic utilizes progressively more sophisticated algorithms for synthetic data generation depending on the volume of raw data available to train the model. At the very basic level, when there are 0-300 respondents in the raw data, Kinetic synthetic datasets are generated by randomly sampling response options for every individual question included in the dataset aligned with the data schema. As we acquire 300 or more responses, we utilize the models outlined in the toolkit to generate higher fidelity synthetic dataset representing the statistical features of the raw data.</p>
            </FAQSection>

            <FAQSection title='What data will researchers see? How close will that be to the raw data?' setCurrentSection={setCurrentSection} currentSection={currentSection}>
                <p>The quality of the synthetic datasets will depend on how many participants are included in the raw data. For newly deployed activities with fewer than 300 respondents, the synthetic dataset will be aligned with the data schema of the task and involve random sampling of the response options such that researchers can develop their analytic scripts without accounting for the statistical features. As the task reaches over 300 respondents, the quality of synthetic data progressively increases to incorporate the statistical features of the raw data.</p>
            </FAQSection>

            <FAQSection title='What if I still want direct access to data?' setCurrentSection={setCurrentSection} currentSection={currentSection}>
                <p>Kinetic will work with its members on a case-by-case basis to provide access to real data, subject to additional training - so that important safeguards, monitoring, and design-enforced limitations are in place for proper compliance with our learners' right to privacy and data security.</p>
            </FAQSection>

            <FAQSection title='What studies should I select for my analysis?' setCurrentSection={setCurrentSection} currentSection={currentSection}>
                <p>The studies you see are both your own studies and studies that have been shared by our own researcher community. Meaning that you’re free to mix and match as many studies as are relevant for your research question at the time. Simply hover over the info icon next to each study for a brief insight into what the study investigates.</p>
            </FAQSection>

            <FAQSection title='What are Study Types?' setCurrentSection={setCurrentSection} currentSection={currentSection}>
                <p>Study types are simply a way to help categorize and more easily identify studies on Kinetic.</p>
                <p>
                    <strong>Cognitive Task & Assessment - </strong>
                    <span>Measures of human cognition, such as working memory, reasoning, and problem-solving, as well as prior knowledge and skills</span>
                </p>

                <p>
                    <strong>Learner Characteristics - </strong>
                    <span>Individual differences measures related to learning and education that provide insight into who is the learner</span>
                </p>

                <p>
                    <strong>Learning Research - </strong>
                    <span>Learning and educational studies, such as A/B/N tests, quasi experiments, and single-domain interventional research</span>
                </p>

                <p>
                    <strong>Product & Organizational Research - </strong>
                    <span>Surveys, assessments, and/or interventions related to understanding learner needs, such as product development and UX design</span>
                </p>

                <p>
                    <strong>Transfer of Learning Research - </strong>
                    <span>Interventions that assess learning or other outcomes across domains</span>
                </p>
            </FAQSection>

            <FAQSection title='What will happen next?' setCurrentSection={setCurrentSection} currentSection={currentSection}>
                <ol>
                    <Box direction='column' gap>
                        <li>Once you set up the basics of your analysis, you will be able to move on into the process of creating your own script in RStudio (an open-source statistical tool).</li>
                        <li>In RStudio you’ll be able to access our hosted container via cloud service where you will see a simulated dataset (synthetic data) that was carefully crafted based on the studies you have chosen to analyze.</li>
                        <li>Against this simulated dataset, you will be able to write your intended script for data analysis.</li>
                        <li>Kinetic will then run your script against real data, and return aggregate knowledge back to you.</li>
                    </Box>
                </ol>
            </FAQSection>
        </Box>
    )
}

export const FAQSection: FCWC<{
    title: string,
    currentSection: string,
    setCurrentSection: (title: string) => void,
}> = ({ title, currentSection, setCurrentSection, children }) => {
    const expanded = currentSection == title
    return (
        <Box className='py-1 h-auto' direction='column' css={{ minHeight: 'auto' }}>
            <Box justify='between' onClick={() => expanded ? setCurrentSection('') : setCurrentSection(title)} className='cursor-pointer'>
                <span className='fw-bold'>{title}</span>

                <Button link>
                    <Icon height={24} icon={expanded ? 'chevronUp' : 'chevronDown'}/>
                </Button>
            </Box>

            {expanded &&
                <div className='py-2'>
                    {children}
                </div>
            }
            <hr/>
        </Box>
    )
}
