/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v1/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Analysis } from './Analysis';
import {
    AnalysisFromJSON,
    AnalysisFromJSONTyped,
    AnalysisToJSON,
} from './Analysis';

/**
 * 
 * @export
 * @interface AddAnalysis
 */
export interface AddAnalysis {
    /**
     * 
     * @type {Analysis}
     * @memberof AddAnalysis
     */
    analysis?: Analysis;
}

/**
 * Check if a given object implements the AddAnalysis interface.
 */
export function instanceOfAddAnalysis(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddAnalysisFromJSON(json: any): AddAnalysis {
    return AddAnalysisFromJSONTyped(json, false);
}

export function AddAnalysisFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddAnalysis {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'analysis': !exists(json, 'analysis') ? undefined : AnalysisFromJSON(json['analysis']),
    };
}

export function AddAnalysisToJSON(value?: AddAnalysis | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'analysis': AnalysisToJSON(value.analysis),
    };
}

