/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v1/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BannerNotice } from './BannerNotice';
import {
    BannerNoticeFromJSON,
    BannerNoticeFromJSONTyped,
    BannerNoticeToJSON,
} from './BannerNotice';

/**
 * 
 * @export
 * @interface AddBanner
 */
export interface AddBanner {
    /**
     * 
     * @type {BannerNotice}
     * @memberof AddBanner
     */
    banner?: BannerNotice;
}

/**
 * Check if a given object implements the AddBanner interface.
 */
export function instanceOfAddBanner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddBannerFromJSON(json: any): AddBanner {
    return AddBannerFromJSONTyped(json, false);
}

export function AddBannerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddBanner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'banner': !exists(json, 'banner') ? undefined : BannerNoticeFromJSON(json['banner']),
    };
}

export function AddBannerToJSON(value?: AddBanner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'banner': BannerNoticeToJSON(value.banner),
    };
}

