/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v1/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Reward,
    RewardFromJSON,
    RewardFromJSONTyped,
    RewardToJSON,
} from './Reward';

/**
 * 
 * @export
 * @interface AddReward
 */
export interface AddReward {
    /**
     * 
     * @type {Reward}
     * @memberof AddReward
     */
    reward?: Reward;
}

export function AddRewardFromJSON(json: any): AddReward {
    return AddRewardFromJSONTyped(json, false);
}

export function AddRewardFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddReward {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reward': !exists(json, 'reward') ? undefined : RewardFromJSON(json['reward']),
    };
}

export function AddRewardToJSON(value?: AddReward | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reward': RewardToJSON(value.reward),
    };
}

