/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v1/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Researcher } from './Researcher';
import {
    ResearcherFromJSON,
    ResearcherFromJSONTyped,
    ResearcherToJSON,
} from './Researcher';

/**
 * 
 * @export
 * @interface AddResearcher
 */
export interface AddResearcher {
    /**
     * 
     * @type {Researcher}
     * @memberof AddResearcher
     */
    researcher?: Researcher;
}

/**
 * Check if a given object implements the AddResearcher interface.
 */
export function instanceOfAddResearcher(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddResearcherFromJSON(json: any): AddResearcher {
    return AddResearcherFromJSONTyped(json, false);
}

export function AddResearcherFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddResearcher {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'researcher': !exists(json, 'researcher') ? undefined : ResearcherFromJSON(json['researcher']),
    };
}

export function AddResearcherToJSON(value?: AddResearcher | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'researcher': ResearcherToJSON(value.researcher),
    };
}

