/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v1/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BadgeCertificateResponse
 */
export interface BadgeCertificateResponse {
    /**
     * Base64-encoded PDF data
     * @type {string}
     * @memberof BadgeCertificateResponse
     */
    pdf?: string;
}

/**
 * Check if a given object implements the BadgeCertificateResponse interface.
 */
export function instanceOfBadgeCertificateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BadgeCertificateResponseFromJSON(json: any): BadgeCertificateResponse {
    return BadgeCertificateResponseFromJSONTyped(json, false);
}

export function BadgeCertificateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadgeCertificateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pdf': !exists(json, 'pdf') ? undefined : json['pdf'],
    };
}

export function BadgeCertificateResponseToJSON(value?: BadgeCertificateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pdf': value.pdf,
    };
}

