/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v1/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BannerNotice } from './BannerNotice';
import {
    BannerNoticeFromJSON,
    BannerNoticeFromJSONTyped,
    BannerNoticeToJSON,
} from './BannerNotice';

/**
 * 
 * @export
 * @interface BannersListing
 */
export interface BannersListing {
    /**
     * The banners.
     * @type {Array<BannerNotice>}
     * @memberof BannersListing
     */
    data: Array<BannerNotice>;
}

/**
 * Check if a given object implements the BannersListing interface.
 */
export function instanceOfBannersListing(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function BannersListingFromJSON(json: any): BannersListing {
    return BannersListingFromJSONTyped(json, false);
}

export function BannersListingFromJSONTyped(json: any, ignoreDiscriminator: boolean): BannersListing {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(BannerNoticeFromJSON)),
    };
}

export function BannersListingToJSON(value?: BannersListing | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(BannerNoticeToJSON)),
    };
}

