/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v1/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Researcher } from './Researcher';
import {
    ResearcherFromJSON,
    ResearcherFromJSONTyped,
    ResearcherToJSON,
} from './Researcher';
import type { Stage } from './Stage';
import {
    StageFromJSON,
    StageFromJSONTyped,
    StageToJSON,
} from './Stage';

/**
 * 
 * @export
 * @interface BaseStudy
 */
export interface BaseStudy {
    /**
     * The study name that participants see.
     * @type {string}
     * @memberof BaseStudy
     */
    titleForParticipants?: string;
    /**
     * The study name that only researchers see.
     * @type {string}
     * @memberof BaseStudy
     */
    titleForResearchers?: string;
    /**
     * A short study description.
     * @type {string}
     * @memberof BaseStudy
     */
    shortDescription?: string;
    /**
     * A long study description.
     * @type {string}
     * @memberof BaseStudy
     */
    longDescription?: string;
    /**
     * The tags of the study object, used for grouping and filtering.
     * @type {Array<string>}
     * @memberof BaseStudy
     */
    tags?: Array<string>;
    /**
     * Description of feedback displayed to the user upon study completion
     * @type {string}
     * @memberof BaseStudy
     */
    feedbackDescription?: string;
    /**
     * Freeform id of image that should be displayed on study card
     * @type {string}
     * @memberof BaseStudy
     */
    imageId?: string;
    /**
     * Description of how the study benefits participants
     * @type {string}
     * @memberof BaseStudy
     */
    benefits?: string;
    /**
     * Is the study hidden from participants
     * @type {boolean}
     * @memberof BaseStudy
     */
    isHidden?: boolean;
    /**
     * When the study opens for participation; null means not open.
     * @type {Date}
     * @memberof BaseStudy
     */
    opensAt?: Date | null;
    /**
     * When the study closes for participation; null means does not close.
     * @type {Date}
     * @memberof BaseStudy
     */
    closesAt?: Date | null;
    /**
     * When the study was launched; null means not launched
     * @type {Date}
     * @memberof BaseStudy
     */
    firstLaunchedAt?: Date;
    /**
     * 
     * @type {Researcher}
     * @memberof BaseStudy
     */
    researcherPi?: Researcher;
    /**
     * 
     * @type {Researcher}
     * @memberof BaseStudy
     */
    researcherLead?: Researcher;
    /**
     * Mandatory studies must be completed by all users
     * @type {boolean}
     * @memberof BaseStudy
     */
    isMandatory?: boolean;
    /**
     * Status of the study
     * @type {string}
     * @memberof BaseStudy
     */
    status?: BaseStudyStatusEnum;
    /**
     * How many times the study has been viewed
     * @type {number}
     * @memberof BaseStudy
     */
    viewCount?: number;
    /**
     * Number of times this study has been completed
     * @type {number}
     * @memberof BaseStudy
     */
    readonly completedCount?: number;
    /**
     * The type of study
     * @type {string}
     * @memberof BaseStudy
     */
    studyType?: string;
    /**
     * The study's stages.
     * @type {Array<Stage>}
     * @memberof BaseStudy
     */
    stages?: Array<Stage>;
}


/**
 * @export
 */
export const BaseStudyStatusEnum = {
    Active: 'active',
    Paused: 'paused',
    Scheduled: 'scheduled',
    Draft: 'draft',
    Completed: 'completed'
} as const;
export type BaseStudyStatusEnum = typeof BaseStudyStatusEnum[keyof typeof BaseStudyStatusEnum];


/**
 * Check if a given object implements the BaseStudy interface.
 */
export function instanceOfBaseStudy(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BaseStudyFromJSON(json: any): BaseStudy {
    return BaseStudyFromJSONTyped(json, false);
}

export function BaseStudyFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseStudy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'titleForParticipants': !exists(json, 'title_for_participants') ? undefined : json['title_for_participants'],
        'titleForResearchers': !exists(json, 'title_for_researchers') ? undefined : json['title_for_researchers'],
        'shortDescription': !exists(json, 'short_description') ? undefined : json['short_description'],
        'longDescription': !exists(json, 'long_description') ? undefined : json['long_description'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'feedbackDescription': !exists(json, 'feedback_description') ? undefined : json['feedback_description'],
        'imageId': !exists(json, 'image_id') ? undefined : json['image_id'],
        'benefits': !exists(json, 'benefits') ? undefined : json['benefits'],
        'isHidden': !exists(json, 'is_hidden') ? undefined : json['is_hidden'],
        'opensAt': !exists(json, 'opens_at') ? undefined : (json['opens_at'] === null ? null : new Date(json['opens_at'])),
        'closesAt': !exists(json, 'closes_at') ? undefined : (json['closes_at'] === null ? null : new Date(json['closes_at'])),
        'firstLaunchedAt': !exists(json, 'first_launched_at') ? undefined : (new Date(json['first_launched_at'])),
        'researcherPi': !exists(json, 'researcher_pi') ? undefined : ResearcherFromJSON(json['researcher_pi']),
        'researcherLead': !exists(json, 'researcher_lead') ? undefined : ResearcherFromJSON(json['researcher_lead']),
        'isMandatory': !exists(json, 'is_mandatory') ? undefined : json['is_mandatory'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'viewCount': !exists(json, 'view_count') ? undefined : json['view_count'],
        'completedCount': !exists(json, 'completed_count') ? undefined : json['completed_count'],
        'studyType': !exists(json, 'study_type') ? undefined : json['study_type'],
        'stages': !exists(json, 'stages') ? undefined : ((json['stages'] as Array<any>).map(StageFromJSON)),
    };
}

export function BaseStudyToJSON(value?: BaseStudy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title_for_participants': value.titleForParticipants,
        'title_for_researchers': value.titleForResearchers,
        'short_description': value.shortDescription,
        'long_description': value.longDescription,
        'tags': value.tags,
        'feedback_description': value.feedbackDescription,
        'image_id': value.imageId,
        'benefits': value.benefits,
        'is_hidden': value.isHidden,
        'opens_at': value.opensAt === undefined ? undefined : (value.opensAt === null ? null : value.opensAt.toISOString()),
        'closes_at': value.closesAt === undefined ? undefined : (value.closesAt === null ? null : value.closesAt.toISOString()),
        'first_launched_at': value.firstLaunchedAt === undefined ? undefined : (value.firstLaunchedAt.toISOString()),
        'researcher_pi': ResearcherToJSON(value.researcherPi),
        'researcher_lead': ResearcherToJSON(value.researcherLead),
        'is_mandatory': value.isMandatory,
        'status': value.status,
        'view_count': value.viewCount,
        'study_type': value.studyType,
        'stages': value.stages === undefined ? undefined : ((value.stages as Array<any>).map(StageToJSON)),
    };
}

