/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v1/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAnalysisRun
 */
export interface CreateAnalysisRun {
    /**
     * Message describing run
     * @type {string}
     * @memberof CreateAnalysisRun
     */
    message: string;
}

/**
 * Check if a given object implements the CreateAnalysisRun interface.
 */
export function instanceOfCreateAnalysisRun(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function CreateAnalysisRunFromJSON(json: any): CreateAnalysisRun {
    return CreateAnalysisRunFromJSONTyped(json, false);
}

export function CreateAnalysisRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAnalysisRun {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function CreateAnalysisRunToJSON(value?: CreateAnalysisRun | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

