/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v0/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnvironmentUser
 */
export interface EnvironmentUser {
    /**
     * The user's ID.
     * @type {string}
     * @memberof EnvironmentUser
     */
    readonly userId?: string;
    /**
     * If true, the user is an administrator
     * @type {boolean}
     * @memberof EnvironmentUser
     */
    readonly isAdministrator: boolean;
    /**
     * If true, the user is a researcher
     * @type {boolean}
     * @memberof EnvironmentUser
     */
    readonly isResearcher: boolean;
}

export function EnvironmentUserFromJSON(json: any): EnvironmentUser {
    return EnvironmentUserFromJSONTyped(json, false);
}

export function EnvironmentUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnvironmentUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
        'isAdministrator': json['is_administrator'],
        'isResearcher': json['is_researcher'],
    };
}

export function EnvironmentUserToJSON(value?: EnvironmentUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


