/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v1/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LearningPath } from './LearningPath';
import {
    LearningPathFromJSON,
    LearningPathFromJSONTyped,
    LearningPathToJSON,
} from './LearningPath';

/**
 * 
 * @export
 * @interface LearningPaths
 */
export interface LearningPaths {
    /**
     * The learning paths.
     * @type {Array<LearningPath>}
     * @memberof LearningPaths
     */
    data: Array<LearningPath>;
}

/**
 * Check if a given object implements the LearningPaths interface.
 */
export function instanceOfLearningPaths(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function LearningPathsFromJSON(json: any): LearningPaths {
    return LearningPathsFromJSONTyped(json, false);
}

export function LearningPathsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningPaths {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(LearningPathFromJSON)),
    };
}

export function LearningPathsToJSON(value?: LearningPaths | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(LearningPathToJSON)),
    };
}

