/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v1/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AnalysisListing } from './AnalysisListing';
import {
    AnalysisListingFromJSON,
    AnalysisListingFromJSONTyped,
    AnalysisListingToJSON,
} from './AnalysisListing';

/**
 * 
 * @export
 * @interface ListAnalysis
 */
export interface ListAnalysis {
    /**
     * 
     * @type {AnalysisListing}
     * @memberof ListAnalysis
     */
    analysis?: AnalysisListing;
}

/**
 * Check if a given object implements the ListAnalysis interface.
 */
export function instanceOfListAnalysis(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListAnalysisFromJSON(json: any): ListAnalysis {
    return ListAnalysisFromJSONTyped(json, false);
}

export function ListAnalysisFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAnalysis {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'analysis': !exists(json, 'analysis') ? undefined : AnalysisListingFromJSON(json['analysis']),
    };
}

export function ListAnalysisToJSON(value?: ListAnalysis | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'analysis': AnalysisListingToJSON(value.analysis),
    };
}

