/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v1/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewStage
 */
export interface NewStage {
    /**
     * An integer that describes the sort order for this stage
     * @type {number}
     * @memberof NewStage
     */
    readonly order?: number;
    /**
     * The name of the stage
     * @type {string}
     * @memberof NewStage
     */
    title?: string;
    /**
     * The longer description shown to participants
     * @type {string}
     * @memberof NewStage
     */
    description?: string;
    /**
     * How many days after previous stage will this become available
     * @type {number}
     * @memberof NewStage
     */
    availableAfterDays?: number;
    /**
     * Has the stage been launched
     * @type {boolean}
     * @memberof NewStage
     */
    readonly isCompleted?: boolean;
    /**
     * Can the stage be launched
     * @type {boolean}
     * @memberof NewStage
     */
    readonly isLaunchable?: boolean;
    /**
     * The configuration for a particular kind of stage, e.g. Qualtrics.  See `QualtricsStage`
     * @type {object}
     * @memberof NewStage
     */
    config: object;
    /**
     * How many points the stage is worth
     * @type {number}
     * @memberof NewStage
     */
    points?: number;
    /**
     * How long the stage is (in minutes)
     * @type {number}
     * @memberof NewStage
     */
    durationMinutes?: number;
    /**
     * When the stage opens for participation; null means not open.
     * @type {Date}
     * @memberof NewStage
     */
    opensAt?: Date | null;
    /**
     * When the stage closes for participation; null means does not close.
     * @type {Date}
     * @memberof NewStage
     */
    closesAt?: Date | null;
    /**
     * Feedback types for this stage
     * @type {Array<string>}
     * @memberof NewStage
     */
    feedbackTypes?: Array<string>;
}

/**
 * Check if a given object implements the NewStage interface.
 */
export function instanceOfNewStage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "config" in value;

    return isInstance;
}

export function NewStageFromJSON(json: any): NewStage {
    return NewStageFromJSONTyped(json, false);
}

export function NewStageFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewStage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'order': !exists(json, 'order') ? undefined : json['order'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'availableAfterDays': !exists(json, 'available_after_days') ? undefined : json['available_after_days'],
        'isCompleted': !exists(json, 'is_completed') ? undefined : json['is_completed'],
        'isLaunchable': !exists(json, 'is_launchable') ? undefined : json['is_launchable'],
        'config': json['config'],
        'points': !exists(json, 'points') ? undefined : json['points'],
        'durationMinutes': !exists(json, 'duration_minutes') ? undefined : json['duration_minutes'],
        'opensAt': !exists(json, 'opens_at') ? undefined : (json['opens_at'] === null ? null : new Date(json['opens_at'])),
        'closesAt': !exists(json, 'closes_at') ? undefined : (json['closes_at'] === null ? null : new Date(json['closes_at'])),
        'feedbackTypes': !exists(json, 'feedback_types') ? undefined : json['feedback_types'],
    };
}

export function NewStageToJSON(value?: NewStage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'available_after_days': value.availableAfterDays,
        'config': value.config,
        'points': value.points,
        'duration_minutes': value.durationMinutes,
        'opens_at': value.opensAt === undefined ? undefined : (value.opensAt === null ? null : value.opensAt.toISOString()),
        'closes_at': value.closesAt === undefined ? undefined : (value.closesAt === null ? null : value.closesAt.toISOString()),
        'feedback_types': value.feedbackTypes,
    };
}

