/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v1/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseExport } from './ResponseExport';
import {
    ResponseExportFromJSON,
    ResponseExportFromJSONTyped,
    ResponseExportToJSON,
} from './ResponseExport';

/**
 * 
 * @export
 * @interface ResponsesListing
 */
export interface ResponsesListing {
    /**
     * The responses.
     * @type {Array<ResponseExport>}
     * @memberof ResponsesListing
     */
    data?: Array<ResponseExport>;
}

/**
 * Check if a given object implements the ResponsesListing interface.
 */
export function instanceOfResponsesListing(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponsesListingFromJSON(json: any): ResponsesListing {
    return ResponsesListingFromJSONTyped(json, false);
}

export function ResponsesListingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesListing {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(ResponseExportFromJSON)),
    };
}

export function ResponsesListingToJSON(value?: ResponsesListing | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(ResponseExportToJSON)),
    };
}

