/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kenetic API
 * The kenetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v0/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Study,
    StudyFromJSON,
    StudyFromJSONTyped,
    StudyToJSON,
} from './';

/**
 * 
 * @export
 * @interface Studies
 */
export interface Studies {
    /**
     * The studies.
     * @type {Array<Study>}
     * @memberof Studies
     */
    data?: Array<Study>;
}

export function StudiesFromJSON(json: any): Studies {
    return StudiesFromJSONTyped(json, false);
}

export function StudiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Studies {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(StudyFromJSON)),
    };
}

export function StudiesToJSON(value?: Studies | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(StudyToJSON)),
    };
}


