/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v1/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudyResponses
 */
export interface StudyResponses {
    /**
     * Status of the request
     * @type {string}
     * @memberof StudyResponses
     */
    status: StudyResponsesStatusEnum;
    /**
     * URL(s) to download study responses from
     * @type {Array<string>}
     * @memberof StudyResponses
     */
    responseUrls?: Array<string>;
    /**
     * The reason for the request failure
     * @type {string}
     * @memberof StudyResponses
     */
    error?: string;
}

/**
* @export
* @enum {string}
*/
export enum StudyResponsesStatusEnum {
    Pending = 'pending',
    Complete = 'complete',
    Error = 'error'
}

export function StudyResponsesFromJSON(json: any): StudyResponses {
    return StudyResponsesFromJSONTyped(json, false);
}

export function StudyResponsesFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudyResponses {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'responseUrls': !exists(json, 'response_urls') ? undefined : json['response_urls'],
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function StudyResponsesToJSON(value?: StudyResponses | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'response_urls': value.responseUrls,
        'error': value.error,
    };
}

