/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v1/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserPreferences } from './UserPreferences';
import {
    UserPreferencesFromJSON,
    UserPreferencesFromJSONTyped,
    UserPreferencesToJSON,
} from './UserPreferences';

/**
 * 
 * @export
 * @interface UpdatePreferences
 */
export interface UpdatePreferences {
    /**
     * 
     * @type {UserPreferences}
     * @memberof UpdatePreferences
     */
    preferences?: UserPreferences;
}

/**
 * Check if a given object implements the UpdatePreferences interface.
 */
export function instanceOfUpdatePreferences(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdatePreferencesFromJSON(json: any): UpdatePreferences {
    return UpdatePreferencesFromJSONTyped(json, false);
}

export function UpdatePreferencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePreferences {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'preferences': !exists(json, 'preferences') ? undefined : UserPreferencesFromJSON(json['preferences']),
    };
}

export function UpdatePreferencesToJSON(value?: UpdatePreferences | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'preferences': UserPreferencesToJSON(value.preferences),
    };
}

