/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Kinetic API
 * The Kinetic API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v1/researcher/studies`. While the API does support a default version, that version will change over time and therefore should not be used in production code! 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LearningPath } from './LearningPath';
import {
    LearningPathFromJSON,
    LearningPathFromJSONTyped,
    LearningPathToJSON,
} from './LearningPath';

/**
 * 
 * @export
 * @interface UpdateLearningPath
 */
export interface UpdateLearningPath {
    /**
     * 
     * @type {LearningPath}
     * @memberof UpdateLearningPath
     */
    learningPath?: LearningPath;
}

/**
 * Check if a given object implements the UpdateLearningPath interface.
 */
export function instanceOfUpdateLearningPath(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateLearningPathFromJSON(json: any): UpdateLearningPath {
    return UpdateLearningPathFromJSONTyped(json, false);
}

export function UpdateLearningPathFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateLearningPath {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'learningPath': !exists(json, 'learningPath') ? undefined : LearningPathFromJSON(json['learningPath']),
    };
}

export function UpdateLearningPathToJSON(value?: UpdateLearningPath | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'learningPath': LearningPathToJSON(value.learningPath),
    };
}

