# Use non-slim to have git and build tools installed (faster for lots of runs
# on CI)
FROM ruby:3.0.3

ARG bundler_version

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /code/backend
COPY . /code

RUN gem install bundler --no-document --version $bundler_version && \
    bundle config set no-cache 'true' && \
    bundle config set silence_root_warning 'true'
