#!/usr/bin/env bash

# set -x

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

commit_range="${1:-main}"
if [ ! -z "$2" ]; then
  commit_range="$commit_range..$2"
fi

echo "Checking $commit_range"

# https://dev.to/scienta/get-changed-files-in-github-actions-1p36
changed_ruby_files=$(cd backend && git diff --relative --name-only --diff-filter=ACMRT $commit_range | grep -E ".*\.rb$" | xargs)

if [[ -z "${changed_ruby_files// }" ]]; then
  echo "No files to lint with Rubocop"
else
  docker run -v $DIR/..:/code \
             -w /code \
             openstax/labs.backend.ci:latest \
             /bin/bash -c "cd backend; bundle config path vendor/bundle; bundle install; bundle exec rubocop $changed_ruby_files --disable-pending-cops"
fi
