#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

docker run -it \
           -v $DIR/..:/code \
           -w /code \
           openstax/labs.backend:latest \
           "$@"
